//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdata
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string email { get; set; }
        public Nullable<long> mnumber { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<int> isinacitive { get; set; }
    }
}
